--Criação do usuário C##AGM
CREATE USER C##AGM IDENTIFIED BY "123Fatec" container=all;

--Permissões
GRANT UNLIMITED TABLESPACE TO C##AGM;
GRANT CONNECT, RESOURCE TO C##AGM;
GRANT CREATE SESSION TO C##AGM;

--Criação das tabelas
CREATE TABLE C##AGM.FUNCIONARIO
(
	"ID" NUMBER(6,0),
	"RGF" VARCHAR(7),
    "NOME" VARCHAR (255),
    "CARGO" VARCHAR (255)
);

CREATE TABLE C##AGM.ITEMRENDIMENTOS
(
	"ID" NUMBER(6,0),
	"NOME" VARCHAR (255),
	"VALOR" NUMBER(8,2) DEFAULT 0,
	"MES" VARCHAR(2),
	"ANO" VARCHAR(5),
	"FUNCIONARIO" NUMBER(6,0)
);

--PRIMARY KEY
ALTER TABLE C##AGM.FUNCIONARIO
	ADD CONSTRAINT PK_FNC PRIMARY KEY (ID);
	
ALTER TABLE C##AGM.ITEMRENDIMENTOS
	ADD CONSTRAINT PK_IRN PRIMARY KEY (ID);

--FOREING KEY	
ALTER TABLE C##AGM.ITEMRENDIMENTOS -- RELACIONAMENTO N-1 (FNC - IRN)
	ADD CONSTRAINT FK_IRN_FNC FOREIGN KEY (FUNCIONARIO) REFERENCES C##AGM.FUNCIONARIO(ID);
    
-- Criação da sequence
CREATE SEQUENCE C##AGM.SQ_FNC 
INCREMENT BY 1 
START WITH 1 
NOCACHE
;

CREATE SEQUENCE C##AGM.SQ_IRN 
INCREMENT BY 1 
START WITH 1 
NOCACHE
;

-- Triggers para pegar valor da sequence
create or replace
TRIGGER C##AGM.TG_SQ_FNC
BEFORE INSERT ON C##AGM.FUNCIONARIO
FOR EACH ROW
BEGIN
  :new.ID := C##AGM.SQ_FNC.NEXTVAL;
END;
/

create or replace
TRIGGER C##AGM.TG_SQ_IRN
BEFORE INSERT ON C##AGM.ITEMRENDIMENTOS
FOR EACH ROW
BEGIN
  :new.ID := C##AGM.SQ_IRN.NEXTVAL;
END;

